# Generated by Django 3.1.3 on 2021-08-17 07:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_vendor_is_listing_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=ckeditor.fields.RichTextField(help_text='Description'),
        ),
    ]
