# Generated by Django 3.1.3 on 2021-08-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210817_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='short_description',
            field=models.TextField(blank=True, help_text='Short Description', null=True),
        ),
    ]
