# Generated by Django 3.1.3 on 2021-08-04 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_auto_20210727_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='price_for',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='vendor_name',
        ),
    ]
