# Generated by Django 3.1.3 on 2021-08-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_auto_20210804_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='review_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
