# Generated by Django 3.1.3 on 2021-09-06 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_listing_review_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='review_id',
        ),
        migrations.AlterField(
            model_name='draftlisting',
            name='label',
            field=models.CharField(blank=True, choices=[('Elite', 'Elite'), ('In Demand', 'In Demand'), ('Our Recommendation', 'Our Recommendation'), ('Most Booked', 'Most Booked'), ('Trending', 'Trending'), ('Popular', 'Popular'), ('Best Deal', 'Best Deal'), ('Best Offer', 'Best Offer')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='label',
            field=models.CharField(blank=True, choices=[('Elite', 'Elite'), ('In Demand', 'In Demand'), ('Our Recommendation', 'Our Recommendation'), ('Most Booked', 'Most Booked'), ('Trending', 'Trending'), ('Popular', 'Popular'), ('Best Deal', 'Best Deal'), ('Best Offer', 'Best Offer')], max_length=20, null=True),
        ),
    ]
