# Generated by Django 3.1.3 on 2021-09-06 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0005_auto_20210906_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='review_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
