# Generated by Django 3.1.3 on 2021-09-11 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0007_auto_20210910_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingoffer',
            name='offer_title',
            field=models.CharField(default='Offer', max_length=300),
        ),
    ]
