# Generated by Django 3.1.3 on 2021-11-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0009_draftlisting_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingcontact',
            name='request_call',
            field=models.BooleanField(default=False),
        ),
    ]
