# Generated by Django 3.1.3 on 2021-11-25 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0010_listingcontact_request_call'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='photos',
            field=models.ManyToManyField(blank=True, null=True, to='listing.ListingPhoto'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='videos',
            field=models.ManyToManyField(blank=True, null=True, to='listing.ListingVideo'),
        ),
    ]
