# Generated by Django 3.1.3 on 2021-07-27 08:13

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile', models.BigIntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DestinationWedding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goa', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('jaipur', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('udaipur', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('jim_corbet', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('planning_decor', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TPP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tand_c', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('t_pp', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('shipping_policy', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('refund_policy', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('some_policy', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('contact', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
