# Generated by Django 3.1.3 on 2022-01-09 13:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0012_auto_20211125_1225'),
        ('home', '0002_auto_20210906_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Landing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('budget', models.IntegerField(blank=True, null=True)),
                ('mobile', models.BigIntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('read', models.BooleanField(default=False)),
                ('listing_parent_category', models.ManyToManyField(null=True, to='listing.ParentListingCategory')),
                ('listing_sub_category', models.ManyToManyField(null=True, to='listing.ListingCategory')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
