# Generated by Django 3.1.3 on 2022-01-17 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0012_auto_20211125_1225'),
        ('home', '0003_landing'),
    ]

    operations = [
        migrations.AddField(
            model_name='landing',
            name='wedding_date',
            field=models.CharField(choices=[('Within this month', 'Within this month'), ('In next 2-3 months', 'In next 2-3 months'), ('In next 3-6 months', 'In next 3-6 months'), ('After around 6 months', 'After around 6 months')], default=None, max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name='landing',
            name='budget',
        ),
        migrations.CreateModel(
            name='ListingCategoryBudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_price', models.IntegerField(blank=True, default=0, null=True)),
                ('max_price', models.IntegerField(blank=True, null=True)),
                ('listing_sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listing.listingcategory')),
            ],
        ),
        migrations.AddField(
            model_name='landing',
            name='budget',
            field=models.ManyToManyField(blank=True, to='home.ListingCategoryBudget'),
        ),
    ]
