# Generated by Django 3.1.3 on 2021-07-27 08:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CancelMiniOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancel_requested', models.BooleanField(default=True)),
                ('cancel_status', models.CharField(choices=[('Processing Cancel Request', 'Processing Cancel Request'), ('CANCEL Denied', 'CANCEL Denied'), ('Cancel Granted', 'Cancel Granted')], default='Processing Cancel Request', max_length=50)),
                ('cancel_granted', models.BooleanField(default=False)),
                ('cancel_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('cancel_reason', models.CharField(blank=True, choices=[('Not Needed', 'Not Needed'), ('Ordered Wrong Product', 'Ordered Wrong Product'), ('Receiving To Late', 'Receiving To Late'), ('Select Different Payment Method', 'Select Different Payment Method'), ('Other', 'Other')], max_length=50, null=True)),
                ('review_description', models.TextField(help_text='Please Describe in detail reason of cancel.')),
            ],
            options={
                'ordering': ['-cancel_date'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15, unique=True)),
                ('discount_percent', models.FloatField()),
                ('minimum_order_amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CouponCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('discount_amount', models.FloatField(null=True)),
                ('used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MiniOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_ref_number', models.CharField(default='ORD-100000', max_length=15)),
                ('mini_order_ref_number', models.CharField(default='MORN-100000', max_length=15, unique=True)),
                ('ordered_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('ordered', models.BooleanField(default=False)),
                ('order_status', models.CharField(choices=[('Preparing', 'Preparing'), ('Shipping', 'Shipping'), ('Delivered', 'Delivered'), ('RETURNED', 'RETURNED'), ('CANCELED', 'CANCELED')], default='Preparing', max_length=50)),
                ('delivered_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('return_window', models.DateTimeField(default=django.utils.timezone.now)),
                ('return_requested', models.BooleanField(default=False)),
                ('cancel_requested', models.BooleanField(default=False)),
                ('payment_method', models.CharField(default='Online by card', max_length=30)),
            ],
            options={
                'ordering': ['-ordered_date_time'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=200, null=True)),
                ('coupon_used', models.BooleanField(default=False)),
                ('order_ref_number', models.CharField(default='ORD-100000', max_length=15, unique=True)),
                ('ordered_date_time', models.DateTimeField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ordered', models.BooleanField(default=False)),
                ('received', models.BooleanField(blank=True, default=False, null=True)),
                ('payment_method', models.CharField(default='Online by card', max_length=30)),
                ('taxes', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['-ordered_date_time'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=200)),
                ('payment_id', models.CharField(max_length=200)),
                ('amount', models.FloatField()),
                ('amount_paid', models.FloatField()),
                ('currency', models.CharField(max_length=50)),
                ('paid', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ReturnMiniOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_requested', models.BooleanField(default=True)),
                ('return_status', models.CharField(choices=[('Processing Return Request', 'Processing Return Request'), ('Item Received by Vendor', 'Item Received by Vendor'), ('Return Denied', 'Return Denied'), ('Return Granted', 'Return Granted')], default='Processing Return Request', max_length=50)),
                ('return_granted', models.BooleanField(default=False)),
                ('return_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('return_reason', models.CharField(blank=True, choices=[('Damaged', 'Damaged'), ('Expired', 'Expired'), ('Ordered Wrong Item', 'Ordered Wrong Item'), ('Received Wrong Item', 'Received Wrong Item'), ('Received Wrong Brand Item', 'Received Wrong Brand Item'), ('Other', 'Other')], max_length=50, null=True)),
                ('review_description', models.TextField(help_text='Please Describe in detail reason of return.')),
                ('return_mini_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.miniorder')),
            ],
            options={
                'ordering': ['return_date'],
            },
        ),
    ]
