# Generated by Django 3.1.3 on 2021-07-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210727_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancelminiorder',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='miniorder',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='returnminiorder',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
