# Generated by Django 3.1.3 on 2021-07-27 08:13

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FunctionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='parent_category')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('label', models.CharField(blank=True, choices=[('Sale', 'Sale'), ('New Arrival', 'New Arrival'), ('Trending', 'Trending'), ('Top Selling', 'Top Selling'), ('Best Deals', 'Best Deals'), ('Recommendation', 'Recommendation'), ('Popular', 'Popular')], help_text='Item is of Sale, New Arrival etc or leave it blank for no label.                                         (Label will be displayed over a item.)', max_length=50, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('stock_no', models.IntegerField(blank=True, help_text='Qty of stock!', null=True)),
                ('short_description', ckeditor.fields.RichTextField(blank=True, help_text='To describe product in short', null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, help_text='Overview product', null=True)),
                ('vendor_name', models.CharField(blank=True, max_length=200, null=True)),
                ('image_main', models.ImageField(blank=True, null=True, upload_to='products')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='products')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='products')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='products')),
                ('image_5', models.ImageField(blank=True, null=True, upload_to='products')),
                ('image_6', models.ImageField(blank=True, null=True, upload_to='products')),
                ('image_7', models.ImageField(blank=True, null=True, upload_to='products')),
                ('image_8', models.ImageField(blank=True, null=True, upload_to='products')),
                ('image_9', models.ImageField(blank=True, null=True, upload_to='products')),
                ('image_10', models.ImageField(blank=True, null=True, upload_to='products')),
                ('image_main_link', models.URLField(blank=True, null=True)),
                ('image_2_link', models.URLField(blank=True, null=True)),
                ('image_3_link', models.URLField(blank=True, null=True)),
                ('image_4_link', models.URLField(blank=True, null=True)),
                ('image_5_link', models.URLField(blank=True, null=True)),
                ('image_6_link', models.URLField(blank=True, null=True)),
                ('image_7_link', models.URLField(blank=True, null=True)),
                ('image_8_link', models.URLField(blank=True, null=True)),
                ('image_9_link', models.URLField(blank=True, null=True)),
                ('image_10_link', models.URLField(blank=True, null=True)),
                ('video_1', models.URLField(blank=True, null=True)),
                ('video_2', models.URLField(blank=True, null=True)),
                ('video_3', models.URLField(blank=True, null=True)),
                ('video_4', models.URLField(blank=True, null=True)),
                ('video_5', models.URLField(blank=True, null=True)),
                ('video_6', models.URLField(blank=True, null=True)),
                ('video_7', models.URLField(blank=True, null=True)),
                ('video_8', models.URLField(blank=True, null=True)),
                ('video_9', models.URLField(blank=True, null=True)),
                ('video_10', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('trending', models.BooleanField(default=False)),
                ('luxury_couture', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'products_product',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('color_code', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('review_description', models.TextField()),
                ('rating', models.FloatField(choices=[(1, 1), (1.5, 1.5), (2, 2), (2.5, 2.5), (3, 3), (3.5, 3.5), (4, 4), (4.5, 4.5), (5, 5)], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('size', 'size'), ('color', 'color')], default='size', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('color_code', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('product_size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productsize')),
            ],
        ),
    ]
